# Version will be manually specified through MusicallyApi/MusicallyApi.csproj instead of CI versioning.

branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore "src-musically" -v Minimal

build_script:
  - dotnet build "src-musically\MusicallyApi" -c Release
  
after_build:
  - dotnet pack "src-musically\MusicallyApi" -c Release --no-build -o artifacts
  
artifacts:
  - path: .\**\artifacts\*.nupkg
  
only_commits:
  files:
    - src-musically/